# Generated by Django 5.0.6 on 2024-06-13 21:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('IdCliente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NomeCliente', models.CharField(max_length=255)),
                ('TelefoneCliente', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('IdMarca', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RelogioCor',
            fields=[
                ('IdCor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('IdVendedor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NomeVendedor', models.CharField(max_length=255)),
                ('TelefoneVendedor', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Relogio',
            fields=[
                ('IdRelogio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Preco', models.IntegerField()),
                ('Garantia', models.CharField(max_length=30)),
                ('Referencia', models.CharField(max_length=30)),
                ('IdMarca', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='estoque.marca')),
                ('IdCor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='estoque.relogiocor')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('IdEstoque', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Quantidade', models.IntegerField()),
                ('DataAtualizacao', models.DateField(auto_now_add=True)),
                ('IdRelogio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='estoque.relogio')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('IdVenda', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('MetodoPag', models.CharField(max_length=50)),
                ('Parcelas', models.IntegerField()),
                ('DataVenda', models.DateField(auto_now_add=True)),
                ('IdCliente', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='estoque.cliente')),
                ('IdVendedor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='estoque.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='ControleVenda',
            fields=[
                ('IdControleVenda', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('IdRelogio', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='estoque.relogio')),
                ('IdVenda', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='estoque.venda')),
            ],
        ),
    ]
